server:
  port: 8081

spring:
  application:
    name: AccountService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankingapplication
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defeaultzone: http://localhost:8761/eureka/
        instance:
          hostname: localhost
